### ISSUE TITLE
Wrong hint label positioning if element has negative margin

### ISSUE THREAD

**Issue by fanglingsu** [fanglingsu/vimb#507]
### Steps to reproduce
Open http://git.exherbo.org/summer/ and start hinting by hitting `f`.

### Expected behaviour
Hint label should be placed on the rupper left corner of the hinted element.

### Actual behaviour
The hint labels are displaced towards top.

It seems that this is caused by negative margin set in the links.
```css
a {
    padding: 10em;
    marign: -10em;
}
```
