### ISSUE TITLE
styling search hints

### ISSUE THREAD

**Issue by AdrienLemaire** [fanglingsu/vimb#599]
### Steps to reproduce
```
$ vimb --bug-info
Version:         3.6.0
WebKit compile:  2.26.2
WebKit run:      2.26.3
GTK compile:     3.24.13
GTK run:         3.24.13
libsoup compile: 2.68.3
libsoup run:     2.68.3
Extension dir:   /usr/lib/vimb
```

style.css
```css
*[vimbhint^='hint'] {
    color: #de935f !important;
}
*[vimbhint='hint focus'] {
    background-color: #de935f !important;
    color: #1d1f21 !important;
}
```

### Expected behaviour
searching for text in the page with `/` should highlight all patterns in orange

### Actual behaviour
Seeing patterns in bright yellow and selected text in dark blue
![b](https://user-images.githubusercontent.com/260983/73506451-f9daee80-4418-11ea-9432-0ce0e56f740d.png)

Note: Styling for link search with `f` works fine
![c](https://user-images.githubusercontent.com/260983/73506573-4a524c00-4419-11ea-8dda-92c41cdd7aa0.png)

Maybe different css rules need to be applied for the styling of searched patterns, but I couldn't find an example in the manpage or the github issues.

**Comment by fanglingsu** [comment]
@AdrienLemaire the yellow comes from webkit and according to https://stackoverflow.com/a/41244420 there is no way we can change this. The blue background on current search result can be altered by
```css
::selection {
    background: red;
}
```
